Update

diff --git a/.local/bin/nb b/.local/bin/nb
--- a/.local/bin/nb
+++ b/.local/bin/nb
@@ -2,36 +2,36 @@
 set git_cmd git -C $ZK_NOTEBOOK_DIR
 
 function handle_git_error
-	echo "Error running git command."
-	return
+    echo "Error running git command."
+    return
 end
 
 if test (count $argv) -eq 0
-	zk edit --sort modified --interactive
-	return
+    zk edit --sort modified --interactive
+    return
 end
 
 switch $argv[1]
-	case "status" "add" "commit" "push" "pull" "log" "diff"
-		$git_cmd $argv
-		return
-	case "sync"
-		$git_cmd add .
-		        
-		if ! $git_cmd diff --cached --quiet
-			$git_cmd commit -m "tmp"
-			$git_cmd pull --rebase
-			
-			set summary ($git_cmd diff --cached --shortstat HEAD~1)
-			$git_cmd commit --amend -m "Synced changes: $summary."
-		else
-			$git_cmd pull --rebase
-			echo "No changes to commit."
-			return
-		end
-		
-		$git_cmd push
-		return
+    case status add commit push pull log diff
+        $git_cmd $argv
+        return
+    case sync
+        $git_cmd add .
+
+        if ! $git_cmd diff --cached --quiet
+            $git_cmd commit -m tmp
+            $git_cmd pull --rebase
+
+            set summary ($git_cmd diff --cached --shortstat HEAD~1)
+            $git_cmd commit --amend -m "Synced changes: $summary."
+        else
+            $git_cmd pull --rebase
+            echo "No changes to commit."
+            return
+        end
+
+        $git_cmd push
+        return
 end
 
 zk $argv
diff --git a/.local/bin/set_colors b/.local/bin/set_colors
--- a/.local/bin/set_colors
+++ b/.local/bin/set_colors
@@ -3,8 +3,8 @@
 set -l palette "$XDG_CONFIG_HOME/colors"
 
 if not test -f $palette
-	echo "Could not find palette: $palette"
-	exit 1
+    echo "Could not find palette: $palette"
+    exit 1
 end
 
 set -l foreground_esc "\033]10;%s\007"
@@ -13,36 +13,36 @@ set -l cursor_esc "\033]12;%s\007"
 set -l color_esc "\033]4;%d;%s\007"
 
 function print_esc
-	if set -q TMUX
-		printf "\033Ptmux;\033%s\033\\" $argv
-	else
-		printf $argv
-	end
+    if set -q TMUX
+        printf "\033Ptmux;\033%s\033\\" $argv >/dev/tty
+    else
+        printf $argv >/dev/tty
+    end
 end
 
 while read -l line
-	set line (echo $line | string replace -r ";.*" "")
+    set line (echo $line | string replace -r ";.*" "")
 
-	if test -z "$line"
-		continue	
-	end
+    if test -z "$line"
+        continue
+    end
 
-	set parts (echo $line | string split "=")
+    set parts (echo $line | string split "=")
 
-	set key (echo $parts[1] | string trim)
-	set value (echo $parts[2] | string trim)
+    set key (string trim $parts[1])
+    set value (string trim $parts[2])
 
-	# echo "Key: $key, Value: $value"
+    # echo "Key: $key, Value: $value"
 
-	switch $key
-		case "cursor"
-			print_esc (printf $cursor_esc $value)
-		case "background"
-			print_esc (printf $background_esc $value)
-		case "foreground"
-			print_esc (printf $foreground_esc $value)
-		case "color*"
-			set idx (echo $key | string replace -r "color" "")
-			print_esc (printf $color_esc $idx $value)
-	end
-end < $palette
+    switch $key
+        case cursor
+            print_esc (printf $cursor_esc $value)
+        case background
+            print_esc (printf $background_esc $value)
+        case foreground
+            print_esc (printf $foreground_esc $value)
+        case "color*"
+            set idx (echo $key | string replace -r "color" "")
+            print_esc (printf $color_esc $idx $value)
+    end
+end <$palette
